device:
  layer: rpi3
  hostname: dogpi
  user1: operator
  user1sudo: nopasswd

image:
  layer: image-rpios
  boot_part_size: 200%
  root_part_size: 8G
  name: liquid-rpi3-lite
  compression: zstd

layer:
  base: trixie-minbase
  liquid: liquid-headless-kit

liquid:
  repo_url: https://github.com/atyrode/liquid.git
  repo_ref: main
  runtime_branch: main
  ohmyzsh_url: https://github.com/ohmyzsh/ohmyzsh.git
  ohmyzsh_ref: 5ef67beadbe371d7f4ed3a7456240e0fd46608ce

ssh:
  pubkey_only: n
