#!/usr/bin/env bash
set -euo pipefail

# rpi-image-gen v2.6.0 writes root=/dev/disk/by-slot/system for image-rpios.
# That slot symlink can disappear after root partition expansion, leaving the Pi
# unable to find its root filesystem. Use the filesystem labels generated by the
# same image layer instead.
setup_script="${IGconf_image_assetdir:?}/setup.sh"
test -f "$setup_script"

cat > "$setup_script" <<'SETUP_EOF'
#!/bin/bash
set -eu

LABEL="$1"

case "$LABEL" in
   ROOT)
      case "$IGconf_image_rootfs_type" in
         ext4)
            cat <<'EOF' > "$IMAGEMOUNTPATH/etc/fstab"
/dev/disk/by-label/ROOT  /  ext4 rw,relatime,errors=remount-ro,commit=30 0 1
EOF
            ;;
         btrfs)
            cat <<'EOF' > "$IMAGEMOUNTPATH/etc/fstab"
/dev/disk/by-label/ROOT  /  btrfs defaults 0 0
EOF
            ;;
         *)
            ;;
      esac

      cat <<'EOF' >> "$IMAGEMOUNTPATH/etc/fstab"
/dev/disk/by-label/BOOT  /boot/firmware  vfat defaults,rw,noatime,errors=remount-ro 0 2
EOF
      ;;
   BOOT)
      sed -i "s|root=\([^ ]*\)|root=/dev/disk/by-label/ROOT|" "$IMAGEMOUNTPATH/cmdline.txt"
      ;;
   *)
      ;;
esac
SETUP_EOF

chmod 0755 "$setup_script"
